In [3]:
import pandas as pd
import numpy as np
import datetime as dt
from sklearn.linear_model import LinearRegression, Lasso, ElasticNet
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

def regression_metrics(y_true, y_pred, shift, alphaval, ratio):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = mean_squared_error(y_true, y_pred) ** 0.5
    r2 = r2_score(y_true, y_pred)

    # MAPE (avoid division by zero by adding a tiny number)
    eps = 1e-6
    mape = np.mean(np.abs((y_true - y_pred) / (np.abs(y_true) + eps))) * 100.0

    return {"MAE": mae, "RMSE": rmse, "R2": r2, "MAPE(%)": mape, "Minutes Shifted": shift*5, "Alpha Value": alphaval, "L1 Ratio": ratio}

def byHour(df):

  df["DateTime"] = pd.to_datetime(df["DateTime"])

  df['Hour'] = df['DateTime'].apply(lambda n: n.hour)
  df['Date'] = df['DateTime'].apply(lambda n: n.date())
  dates = df['Date'].unique()

  res = []
  for d in dates:
    temp = df.where(df['Date'] == d).groupby(['Hour'])[['Speed',
                                                        'Volume',
                                                        'Volume Per Lane',
                                                        'Occupancy']].mean().reset_index()
    temp['Date'] = d
    temp['DateTime'] = temp.apply(lambda row:
                                  pd.to_datetime(f"{row['Date']}" + " " +
                                  f"{dt.time(hour=int(row['Hour'])).strftime('%H:%M:%S')}"), axis = 1)
    res.append(temp)

  return res

def timelag(df1, df2, shiftn):
  df1["DateTime"] = pd.to_datetime(df1["DateTime"])
  df2["DateTime"] = pd.to_datetime(df2["DateTime"])
  df1[['SpeedLag1',
       'VolLag1',
       'VPLLag1',
       'OccLag1']] = df2[['Speed',
                          'Volume',
                          'Volume Per Lane',
                          'Occupancy']].shift(shiftn)
  df1 = df1.dropna().reset_index(drop=True)

  if 'Unnamed: 0' in df1.columns:
    df1 = df1.drop('Unnamed: 0', axis = 1)
  return df1

def dfSort(df):
  sorted = df.dropna().reset_index(drop=True)
  cutoff_train = sorted["DateTime"].quantile(0.70)
  cutoff_val= sorted["DateTime"].quantile(0.85)

  train = sorted[sorted["DateTime"] < cutoff_train]
  val   = sorted[(sorted["DateTime"] >= cutoff_train) & (sorted["DateTime"] < cutoff_val)]
  test  = sorted[sorted["DateTime"] >= cutoff_val]
  return sorted, train, val, test

def trainModel(traindat, valdat, testdat, model, pred_val, shiftn, alpha, ratio):
  xval = traindat[['SpeedLag1', 'VolLag1', 'VPLLag1', 'OccLag1']]
  model.fit(xval, traindat[pred_val].to_frame())

  y_val   = valdat[pred_val].values
  y_test = testdat[pred_val].values

  pred_val = model.predict(valdat[['SpeedLag1', 'VolLag1', 'VPLLag1', 'OccLag1']])
  pred_test = model.predict(testdat[['SpeedLag1', 'VolLag1', 'VPLLag1', 'OccLag1']])

  lin_val = regression_metrics(y_val, pred_val, shiftn, alpha, ratio)
  lin_test = regression_metrics(y_test, pred_test, shiftn, alpha, ratio)

  res = pd.DataFrame([lin_val, lin_test], index=[f"{model} (Val)", f"{model} (Test)"])
  return res

In [4]:
filename_i5 = '005es16732_loop_cloutput.csv'
filename_520 = '520es00972_loop_cloutput.csv'

dfi5 = pd.read_csv(filename_i5)
df520 = pd.read_csv(filename_520)

In [82]:
shiftns =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
alphavals = 0.1 #[0.1, 1, 5, 10, 20, 100, 200, 500] 
l1ratios = 0.45 #[0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]

spdfulllr = []
volfulllr = []
spdfulllas = []
volfulllas = []
spdfulleln = []
volfulleln = []

#Testing of diffrent time shifts

for i in range(len(shiftns)):
    lr = LinearRegression()
    lrlasso = Lasso(alpha=alphavals)
    lreln = ElasticNet(alpha=alphavals, l1_ratio = l1ratios)
    dftemp = timelag(dfi5.copy(), df520.copy(), shiftns[i])
    dftemp_sorted, trainm, valm, testm = dfSort(dftemp)
    resvollr = trainModel(trainm, valm, testm, lr, 'Volume', shiftns[i], alphavals, l1ratios)
    resspdlr = trainModel(trainm, valm, testm, lr, 'Speed', shiftns[i], alphavals, l1ratios)
    resvollas = trainModel(trainm, valm, testm, lrlasso, 'Volume', shiftns[i], alphavals, l1ratios)
    resspdlas = trainModel(trainm, valm, testm, lrlasso, 'Speed', shiftns[i], alphavals, l1ratios)
    resvoleln = trainModel(trainm, valm, testm, lreln, 'Volume', shiftns[i], alphavals, l1ratios)
    resspdeln = trainModel(trainm, valm, testm, lreln, 'Speed', shiftns[i], alphavals, l1ratios)
    volfulllr.append(resvollr)
    spdfulllr.append(resspdlr)
    volfulllas.append(resvollas)
    spdfulllas.append(resspdlas)
    volfulleln.append(resvoleln)
    spdfulleln.append(resspdeln)

#Testing of different alpha values

# for i in range(len(alphavals)):
#     lr = LinearRegression()
#     lrlasso = Lasso(alpha=alphavals[i])
#     lreln = ElasticNet(alpha=alphavals[i], l1_ratio = l1ratios)
#     dftemp = timelag(dfi5.copy(), df520.copy(), shiftns)
#     dftemp_sorted, trainm, valm, testm = dfSort(dftemp)
#     resvollr = trainModel(trainm, valm, testm, lr, 'Volume', shiftns, alphavals[i], l1ratios)
#     resspdlr = trainModel(trainm, valm, testm, lr, 'Speed', shiftns, alphavals[i], l1ratios)
#     resvollas = trainModel(trainm, valm, testm, lrlasso, 'Volume', shiftns, alphavals[i], l1ratios)
#     resspdlas = trainModel(trainm, valm, testm, lrlasso, 'Speed', shiftns, alphavals[i], l1ratios)
#     resvoleln = trainModel(trainm, valm, testm, lreln, 'Volume', shiftns, alphavals[i], l1ratios)
#     resspdeln = trainModel(trainm, valm, testm, lreln, 'Speed', shiftns, alphavals[i], l1ratios)
#     volfulllr.append(resvollr)
#     spdfulllr.append(resspdlr)
#     volfulllas.append(resvollas)
#     spdfulllas.append(resspdlas)
#     volfulleln.append(resvoleln)
#     spdfulleln.append(resspdeln)

#Testing of different L1 ratios

# for i in range(len(l1ratios)):
#     lr = LinearRegression()
#     lrlasso = Lasso(alpha=alphavals)
#     lreln = ElasticNet(alpha=alphavals, l1_ratio = l1ratios[i])
#     dftemp = timelag(dfi5.copy(), df520.copy(), shiftns)
#     dftemp_sorted, trainm, valm, testm = dfSort(dftemp)
#     resvollr = trainModel(trainm, valm, testm, lr, 'Volume', shiftns, alphavals, l1ratios[i])
#     resspdlr = trainModel(trainm, valm, testm, lr, 'Speed', shiftns, alphavals, l1ratios[i])
#     resvollas = trainModel(trainm, valm, testm, lrlasso, 'Volume', shiftns, alphavals, l1ratios[i])
#     resspdlas = trainModel(trainm, valm, testm, lrlasso, 'Speed', shiftns, alphavals, l1ratios[i])
#     resvoleln = trainModel(trainm, valm, testm, lreln, 'Volume', shiftns, alphavals, l1ratios[i])
#     resspdeln = trainModel(trainm, valm, testm, lreln, 'Speed', shiftns, alphavals, l1ratios[i])
#     volfulllr.append(resvollr)
#     spdfulllr.append(resspdlr)
#     volfulllas.append(resvollas)
#     spdfulllas.append(resspdlas)
#     volfulleln.append(resvoleln)
#     spdfulleln.append(resspdeln)

spdfinlr = pd.concat(spdfulllr)
volfinlr = pd.concat (volfulllr)
spdfinlas = pd.concat(spdfulllas)
volfinlas = pd.concat (volfulllas)
spdfineln = pd.concat(spdfulleln)
volfineln = pd.concat (volfulleln)

In [83]:
print('Linear Regression \nTraining to Predict Speed:\n')
display(spdfinlr)

Linear Regression
Training to Predict Speed:

,MAE,RMSE,R2,MAPE(%),Minutes Shifted,Alpha Value,L1 Ratio
LinearRegression() (Val),12.088561,14.162745,0.350764,59.528419,0,0.1,0.45
LinearRegression() (Test),12.881480,15.140483,0.295720,55.572277,0,0.1,0.45
LinearRegression() (Val),12.025565,14.112986,0.355182,59.562077,5,0.1,0.45
LinearRegression() (Test),12.801834,15.058821,0.303346,55.624608,5,0.1,0.45
LinearRegression() (Val),11.981412,14.060064,0.360009,59.595402,10,0.1,0.45
LinearRegression() (Test),12.724134,14.983948,0.310256,55.668749,10,0.1,0.45
LinearRegression() (Val),11.910869,13.992927,0.366106,59.634929,15,0.1,0.45
LinearRegression() (Test),12.652614,14.916633,0.316439,55.714951,15,0.1,0.45
LinearRegression() (Val),11.847119,13.944326,0.370431,59.661550,20,0.1,0.45
LinearRegression() (Test),12.586760,14.850795,0.322460,55.752384,20,0.1,0.45
LinearRegression() (Val),11.812953,13.913964,0.373170,59.705314,25,0.1,0.45
LinearRegression() (Test),12.530768,14.801315,0.326968,55.798534,25,0.1,0.45
LinearRegression() (Val),11.776069,13.872970,0.376858,59.737691,30,0.1,0.45
LinearRegression() (Test),12.462469,14.747371,0.331864,55.838683,30,0.1,0.45
LinearRegression() (Val),11.712583,13.840096,0.379808,59.765662,35,0.1,0.45
LinearRegression() (Test),12.386145,14.696432,0.336472,55.881293,35,0.1,0.45
LinearRegression() (Val),11.669252,13.813447,0.382093,59.773365,40,0.1,0.45
LinearRegression() (Test),12.343553,14.654887,0.340260,55.919198,40,0.1,0.45
LinearRegression() (Val),11.644008,13.792595,0.383957,59.790525,45,0.1,0.45
LinearRegression() (Test),12.295731,14.601788,0.345033,55.950429,45,0.1,0.45
LinearRegression() (Val),11.610303,13.766706,0.386267,59.807131,50,0.1,0.45
LinearRegression() (Test),12.229098,14.552071,0.349485,55.978388,50,0.1,0.45
LinearRegression() (Val),11.588292,13.743202,0.388295,59.818755,55,0.1,0.45
LinearRegression() (Test),12.182877,14.513520,0.352927,56.002569,55,0.1,0.45
LinearRegression() (Val),11.568222,13.748093,0.387859,59.828078,60,0.1,0.45
LinearRegression() (Test),12.154358,14.484998,0.355468,56.020027,60,0.1,0.45

In [86]:
print('Linear Regression \nTraining to Predict Volume:\n')
display(volfinlr)

Linear Regression
Training to Predict Volume:

,MAE,RMSE,R2,MAPE(%),Minutes Shifted,Alpha Value,L1 Ratio
LinearRegression() (Val),13.282284,17.946011,0.718864,4.893931e+07,0,0.1,0.45
LinearRegression() (Test),12.851190,17.263422,0.727148,2.221600e+07,0,0.1,0.45
LinearRegression() (Val),12.993427,17.618926,0.728987,4.894967e+07,5,0.1,0.45
LinearRegression() (Test),12.569994,16.897052,0.738622,2.220518e+07,5,0.1,0.45
LinearRegression() (Val),12.781176,17.368122,0.736647,4.896349e+07,10,0.1,0.45
LinearRegression() (Test),12.314333,16.645158,0.746357,2.219457e+07,10,0.1,0.45
LinearRegression() (Val),12.630434,17.250904,0.740190,4.898241e+07,15,0.1,0.45
LinearRegression() (Test),12.164361,16.444818,0.752426,2.218558e+07,15,0.1,0.45
LinearRegression() (Val),12.479632,17.061102,0.745864,4.899995e+07,20,0.1,0.45
LinearRegression() (Test),12.030709,16.275904,0.757486,2.218370e+07,20,0.1,0.45
LinearRegression() (Val),12.373413,16.934203,0.749631,4.901529e+07,25,0.1,0.45
LinearRegression() (Test),11.925789,16.154985,0.761076,2.217512e+07,25,0.1,0.45
LinearRegression() (Val),12.285281,16.763022,0.754667,4.902574e+07,30,0.1,0.45
LinearRegression() (Test),11.897800,16.132340,0.761745,2.217019e+07,30,0.1,0.45
LinearRegression() (Val),12.225962,16.773603,0.754357,4.904715e+07,35,0.1,0.45
LinearRegression() (Test),11.826648,15.952592,0.767025,2.216734e+07,35,0.1,0.45
LinearRegression() (Val),12.330883,16.775040,0.754243,4.905971e+07,40,0.1,0.45
LinearRegression() (Test),11.910577,16.037421,0.764559,2.216577e+07,40,0.1,0.45
LinearRegression() (Val),12.424437,16.815352,0.753060,4.907738e+07,45,0.1,0.45
LinearRegression() (Test),11.963348,16.030875,0.764751,2.216875e+07,45,0.1,0.45
LinearRegression() (Val),12.535730,16.910706,0.750252,4.909213e+07,50,0.1,0.45
LinearRegression() (Test),12.001006,16.049068,0.764216,2.216623e+07,50,0.1,0.45
LinearRegression() (Val),12.619238,16.958809,0.748831,4.910752e+07,55,0.1,0.45
LinearRegression() (Test),12.074652,16.110249,0.762415,2.216883e+07,55,0.1,0.45
LinearRegression() (Val),12.762135,17.077542,0.745301,4.912116e+07,60,0.1,0.45
LinearRegression() (Test),12.198713,16.178111,0.760410,2.217394e+07,60,0.1,0.45

In [85]:
print('Linear Regression w/ Lasso Regularization\nTraining to Predict Speed:\n')
display(spdfinlas)

Linear Regression w/ Lasso Regularization
Training to Predict Speed:

,MAE,RMSE,R2,MAPE(%),Minutes Shifted,Alpha Value,L1 Ratio
Lasso(alpha=0.1) (Val),12.115476,14.181126,0.349077,43.949554,0,0.1,0.45
Lasso(alpha=0.1) (Test),12.923874,15.151470,0.294698,42.512000,0,0.1,0.45
Lasso(alpha=0.1) (Val),12.050543,14.132200,0.353425,43.710642,5,0.1,0.45
Lasso(alpha=0.1) (Test),12.839116,15.065494,0.302728,42.288070,5,0.1,0.45
Lasso(alpha=0.1) (Val),12.006563,14.079786,0.358212,43.500445,10,0.1,0.45
Lasso(alpha=0.1) (Test),12.758728,14.990280,0.309673,42.059609,10,0.1,0.45
Lasso(alpha=0.1) (Val),11.936682,14.014501,0.364150,43.283616,15,0.1,0.45
Lasso(alpha=0.1) (Test),12.682570,14.922408,0.315910,41.861499,15,0.1,0.45
Lasso(alpha=0.1) (Val),11.866701,13.964108,0.368644,43.060618,20,0.1,0.45
Lasso(alpha=0.1) (Test),12.615437,14.857877,0.321814,41.664210,20,0.1,0.45
Lasso(alpha=0.1) (Val),11.834406,13.933684,0.371392,42.904975,25,0.1,0.45
Lasso(alpha=0.1) (Test),12.557123,14.808341,0.326328,41.429700,25,0.1,0.45
Lasso(alpha=0.1) (Val),11.795272,13.891547,0.375188,42.745599,30,0.1,0.45
Lasso(alpha=0.1) (Test),12.488632,14.752791,0.331373,41.231315,30,0.1,0.45
Lasso(alpha=0.1) (Val),11.735253,13.860706,0.377959,42.557889,35,0.1,0.45
Lasso(alpha=0.1) (Test),12.411774,14.702658,0.335910,41.032783,35,0.1,0.45
Lasso(alpha=0.1) (Val),11.690985,13.834366,0.380220,42.392728,40,0.1,0.45
Lasso(alpha=0.1) (Test),12.367555,14.660156,0.339786,40.847281,40,0.1,0.45
Lasso(alpha=0.1) (Val),11.666988,13.813096,0.382124,42.254069,45,0.1,0.45
Lasso(alpha=0.1) (Test),12.316686,14.606611,0.344600,40.685154,45,0.1,0.45
Lasso(alpha=0.1) (Val),11.630594,13.786245,0.384524,42.063586,50,0.1,0.45
Lasso(alpha=0.1) (Test),12.248631,14.554651,0.349255,40.457185,50,0.1,0.45
Lasso(alpha=0.1) (Val),11.606244,13.762347,0.386589,41.928463,55,0.1,0.45
Lasso(alpha=0.1) (Test),12.204091,14.517545,0.352568,40.285437,55,0.1,0.45
Lasso(alpha=0.1) (Val),11.586889,13.764815,0.386369,41.840926,60,0.1,0.45
Lasso(alpha=0.1) (Test),12.179272,14.495166,0.354563,40.166503,60,0.1,0.45

In [88]:
print('Training to Predict Volume:\n')
display(volfinlas)

Training to Predict Volume:

,MAE,RMSE,R2,MAPE(%),Minutes Shifted,Alpha Value,L1 Ratio
Lasso(alpha=0.1) (Val),13.293473,17.950423,0.718726,4.534736e+07,0,0.1,0.45
Lasso(alpha=0.1) (Test),12.864478,17.266275,0.727058,3.750908e+06,0,0.1,0.45
Lasso(alpha=0.1) (Val),13.004435,17.624287,0.728822,4.601818e+07,5,0.1,0.45
Lasso(alpha=0.1) (Test),12.583446,16.899452,0.738548,4.623327e+06,5,0.1,0.45
Lasso(alpha=0.1) (Val),12.791241,17.373341,0.736489,4.596260e+07,10,0.1,0.45
Lasso(alpha=0.1) (Test),12.327082,16.645115,0.746358,4.577434e+06,10,0.1,0.45
Lasso(alpha=0.1) (Val),12.640826,17.255866,0.740041,4.623712e+07,15,0.1,0.45
Lasso(alpha=0.1) (Test),12.173455,16.445259,0.752413,5.028007e+06,15,0.1,0.45
Lasso(alpha=0.1) (Val),12.488053,17.065963,0.745720,4.682331e+07,20,0.1,0.45
Lasso(alpha=0.1) (Test),12.039486,16.275618,0.757494,5.390789e+06,20,0.1,0.45
Lasso(alpha=0.1) (Val),12.381775,16.939484,0.749475,4.724266e+07,25,0.1,0.45
Lasso(alpha=0.1) (Test),11.935289,16.154316,0.761096,5.936205e+06,25,0.1,0.45
Lasso(alpha=0.1) (Val),12.293119,16.767687,0.754530,4.784954e+07,30,0.1,0.45
Lasso(alpha=0.1) (Test),11.906160,16.129332,0.761834,6.869510e+06,30,0.1,0.45
Lasso(alpha=0.1) (Val),12.232345,16.777599,0.754240,4.798680e+07,35,0.1,0.45
Lasso(alpha=0.1) (Test),11.832168,15.951128,0.767068,7.586344e+06,35,0.1,0.45
Lasso(alpha=0.1) (Val),12.337819,16.779928,0.754100,4.816870e+07,40,0.1,0.45
Lasso(alpha=0.1) (Test),11.916367,16.036469,0.764587,8.078339e+06,40,0.1,0.45
Lasso(alpha=0.1) (Val),12.429229,16.819300,0.752944,4.842995e+07,45,0.1,0.45
Lasso(alpha=0.1) (Test),11.966269,16.029638,0.764787,8.909155e+06,45,0.1,0.45
Lasso(alpha=0.1) (Val),12.540279,16.915040,0.750124,4.835215e+07,50,0.1,0.45
Lasso(alpha=0.1) (Test),12.004822,16.046167,0.764302,9.551195e+06,50,0.1,0.45
Lasso(alpha=0.1) (Val),12.623645,16.962599,0.748718,4.874672e+07,55,0.1,0.45
Lasso(alpha=0.1) (Test),12.076745,16.108315,0.762472,1.010473e+07,55,0.1,0.45
Lasso(alpha=0.1) (Val),12.764433,17.079980,0.745229,4.896536e+07,60,0.1,0.45
Lasso(alpha=0.1) (Test),12.200319,16.177389,0.760431,1.069012e+07,60,0.1,0.45

In [87]:
print('ElasticNet Linear Regression\nTraining to Predict Speed:\n')
display(spdfineln)

ElasticNet Linear Regression
Training to Predict Speed:

,MAE,RMSE,R2,MAPE(%),Minutes Shifted,Alpha Value,L1 Ratio
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.116080,14.181303,0.349061,43.950141,0,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.925393,15.152730,0.294581,42.513938,0,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.051244,14.132442,0.353403,43.711465,5,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.840658,15.066716,0.302615,42.290028,5,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.007221,14.079969,0.358195,43.501150,10,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.760274,14.991512,0.309559,42.061610,10,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",11.937431,14.014695,0.364133,43.284578,15,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.684070,14.923627,0.315798,41.863417,15,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",11.867321,13.964200,0.368636,43.061350,20,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.616963,14.859058,0.321706,41.666232,20,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",11.834993,13.933797,0.371382,42.905650,25,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.558617,14.809548,0.326219,41.431781,25,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",11.795763,13.891609,0.375183,42.746166,30,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.490080,14.753970,0.331266,41.233261,30,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",11.735803,13.860760,0.377955,42.558621,35,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.413165,14.703811,0.335806,41.034668,35,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",11.691494,13.834380,0.380218,42.393453,40,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.369010,14.661297,0.339683,40.849325,40,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",11.667510,13.813090,0.382124,42.254794,45,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.318100,14.607713,0.344501,40.687158,45,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",11.630990,13.786162,0.384531,42.064074,50,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.249916,14.555691,0.349162,40.458895,50,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",11.606650,13.762227,0.386600,41.929054,55,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.205397,14.518573,0.352477,40.287245,55,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",11.586527,13.764943,0.386358,41.840148,60,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.177981,14.494158,0.354653,40.164615,60,0.1,0.45

In [89]:
print('Training to Predict Volume:\n')
display(volfineln)

Training to Predict Volume:

,MAE,RMSE,R2,MAPE(%),Minutes Shifted,Alpha Value,L1 Ratio
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",13.293821,17.950693,0.718717,4.534902e+07,0,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.865177,17.266635,0.727046,3.751449e+06,0,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",13.004879,17.624568,0.728813,4.601959e+07,5,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.584206,16.899866,0.738535,4.624525e+06,5,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.791669,17.373573,0.736482,4.596402e+07,10,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.327841,16.645533,0.746346,4.578091e+06,10,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.641215,17.256137,0.740033,4.623908e+07,15,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.174276,16.445684,0.752400,5.027987e+06,15,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.488436,17.066163,0.745714,4.682512e+07,20,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.040324,16.276062,0.757481,5.391110e+06,20,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.382110,16.939697,0.749468,4.724470e+07,25,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",11.936140,16.154767,0.761082,5.936156e+06,25,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.293518,16.767915,0.754524,4.785156e+07,30,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",11.906986,16.129813,0.761820,6.869664e+06,30,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.232648,16.777793,0.754234,4.798855e+07,35,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",11.832954,15.951573,0.767055,7.586303e+06,35,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.337972,16.780088,0.754095,4.817100e+07,40,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",11.917232,16.036945,0.764573,8.078354e+06,40,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.429397,16.819468,0.752939,4.843134e+07,45,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",11.967003,16.030097,0.764774,8.909526e+06,45,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.540381,16.915143,0.750121,4.835382e+07,50,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.005496,16.046612,0.764289,9.550700e+06,50,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.623628,16.962656,0.748717,4.874832e+07,55,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.077416,16.108773,0.762459,1.010494e+07,55,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Val)",12.764404,17.080011,0.745228,4.896748e+07,60,0.1,0.45
"ElasticNet(alpha=0.1, l1_ratio=0.45) (Test)",12.200984,16.177830,0.760418,1.069005e+07,60,0.1,0.45